kozistr/pytorch_optimizer

- pytorch_optimizer/__init__.py
- pytorch_optimizer/madgrad.py
* Apply AdamW style weight decay
Reference : https://github.com/lessw2020/Best-Deep-Learning-Optimizers
> [Feature] Improve MADGRAD optimizer

- pytorch_optimizer/adabelief.py
- pytorch_optimizer/adabound.py
- pytorch_optimizer/pcgrad.py
- pytorch_optimizer/radam.py
- pytorch_optimizer/ranger21.py
- tests/test_load_optimizers.py
- tests/test_optimizer_parameters.py
- tests/test_optimizers.py
* learning_rate
* weight_decay
* eps 
* betas
> [Test] Add more test cases

- pyproject.toml
- pytorch_optimizer/ranger21.py
- tests/test_optimizer_parameters.py
https://github.com/kozistr/pytorch_optimizer/issues/62
`num_iterations` parameter at `Ranger21` needs a valid integer value, but None. So, it causes a type error when calculating warm-up iterations.
* Not to assign a default value (None) to `num_iterations` parameter
nope
version to 1.1.2
> [Bug] Not to assign a default value (None) to `num_iterations` parameter

- hubconf.py
- pytorch_optimizer/__init__.py
loading optimizers via [`torch.hub.load`](https://pytorch.org/docs/stable/hub.html)
it is inconvenient to define functions one by one, I used a trick using `globals()`.
Change `Callable` to `Type[Optimizer]`. Perhaps this is what you intended. see: [typing.Type](https://docs.python.org/ko/3/library/typing.html#typing.Type)
[example colab](https://colab.research.google.com/drive/1Hc4axLTiNJVwwg8bcyCI-Ti-CUzsA1xR?usp=sharing)
```python
import torch
Adan = torch.hub.load("Bing-su/pytorch_optimizer:hubconf", "Adan")
```
> [Feature] support torch.hub.load

- README.rst
- pyproject.toml
`raw` derive cannot be used due to the security issue e.g. code injection. so building pip package is failed.
nope
version to 1.3.1
> [Docs] fix `raw` derive in RST file

- pyproject.toml
- pytorch_optimizer/adan.py
- tests/test_optimizers.py
forgot to divide into `beta_correation` wehn calculating `perturb`
update version to `v1.3.2`
> [Feature, Fix] Adan optimizer 

- hubconf.py
2.0.0 출시를 축하드립니다.
1. load schedulers
2. torch.hub.list에서 `func`, `optimizer` 감추기
```python
>>> import torch
>>> torch.hub.list("kozistr/pytorch_optimizer")
...
'adan',
'adapnm',
'diffgrad',
'diffrgrad',
'func', # <<<<<<
'lamb',
'lars',
'madgrad',
'nero',
'optimizer', # <<<<<<
'pnm',
'radam',
'ralamb',
'ranger',
'ranger21',
'sgdp',
'shampoo']
```
3. torch.load.help 타겟을 class 자체에서 __init__으로 변경
- before
```python
>>> print(torch.hub.help("kozistr/pytorch_optimizer", "ranger"))
Reference : https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer
Example :
from pytorch_optimizer import Ranger
...
model = YourModel()
optimizer = Ranger(model.parameters())
...
for input, output in data:
optimizer.zero_grad()
loss = loss_function(output, model(input))
loss.backward()
optimizer.step()
```
- …
> [Fix] update hubconf.py

- pytorch_optimizer/optimizer/adabelief.py
- pytorch_optimizer/optimizer/adabound.py
- pytorch_optimizer/optimizer/adamp.py
- pytorch_optimizer/optimizer/adan.py
- pytorch_optimizer/optimizer/adapnm.py
- pytorch_optimizer/optimizer/diffgrad.py
- pytorch_optimizer/optimizer/diffrgrad.py
- pytorch_optimizer/optimizer/gsam.py
- pytorch_optimizer/optimizer/lars.py
- pytorch_optimizer/optimizer/madgrad.py
- pytorch_optimizer/optimizer/radam.py
- pytorch_optimizer/optimizer/ralamb.py
- pytorch_optimizer/optimizer/ranger.py
- pytorch_optimizer/optimizer/ranger21.py
- pytorch_optimizer/optimizer/sgdp.py
- pytorch_optimizer/optimizer/utils.py
> [Refactor] Cleanup the codes

- docs/optimizer_api.rst
- docs/util_api.rst
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/dadapt.py
- pytorch_optimizer/optimizer/shampoo.py
- pytorch_optimizer/optimizer/shampoo_utils.py
- pytorch_optimizer/optimizer/utils.py
- tests/constants.py
- tests/test_gradients.py
- tests/test_load_optimizers.py
- tests/test_optimizer_parameters.py
- tests/test_optimizers.py
- tests/test_utils.py
- tests/utils.py
new optimizers!
- Shampoo Optimizer (related to #100)
bump version into `v2.4.0`
> [Feature] Implements D-Adaptation optimizers

- README.rst
- docs/optimizer_api.rst
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/novograd.py
- tests/constants.py
- tests/test_load_optimizers.py
Implement NovoGrad optimizer
nope
nope
> [Feature] Implement NovoGrad optimizer

- pyproject.toml
- pytorch_optimizer/optimizer/adabelief.py
- pytorch_optimizer/optimizer/adabound.py
- pytorch_optimizer/optimizer/adafactor.py
- pytorch_optimizer/optimizer/adai.py
- pytorch_optimizer/optimizer/adamp.py
- pytorch_optimizer/optimizer/adams.py
- pytorch_optimizer/optimizer/adan.py
- pytorch_optimizer/optimizer/adapnm.py
- pytorch_optimizer/optimizer/alig.py
- pytorch_optimizer/optimizer/apollo.py
- pytorch_optimizer/optimizer/dadapt.py
- pytorch_optimizer/optimizer/diffgrad.py
- pytorch_optimizer/optimizer/diffrgrad.py
- pytorch_optimizer/optimizer/gsam.py
- pytorch_optimizer/optimizer/lamb.py
- pytorch_optimizer/optimizer/lars.py
- pytorch_optimizer/optimizer/lion.py
- pytorch_optimizer/optimizer/madgrad.py
- pytorch_optimizer/optimizer/nero.py
- pytorch_optimizer/optimizer/novograd.py
- pytorch_optimizer/optimizer/pnm.py
- pytorch_optimizer/optimizer/radam.py
- pytorch_optimizer/optimizer/ralamb.py
- pytorch_optimizer/optimizer/ranger.py
- pytorch_optimizer/optimizer/ranger21.py
- pytorch_optimizer/optimizer/sam.py
- pytorch_optimizer/optimizer/sgdp.py
- pytorch_optimizer/optimizer/shampoo.py
- tests/test_optimizers.py
related to #118 
nope
bump version to v2.5.1
> [Fix] `__str__` method supposed to be a function, not property

- pytorch_optimizer/optimizer/ranger21.py
Ranger21 does not go through the 2nd phase if the first parameter does not have a grad. This results in no training happing
We should rather go to the parameter that has a grad which is simply taking the first of the state dict.
> [Fix] Ranger21 not skipping update

- .github/workflows/publish.yml
fix tag name `refs/tags/{tag_name}` to `{tag_name}`
nope
need to re-deploy v2.9.1
> [Fix] tag name

- pytorch_optimizer/optimizer/lookahead.py
The problem is described in #200. In short, `Lookahead` needs to be a subclass of `torch.optim.Optimizer` in order to work with PyTorch Lightning.
Added `torch.optim.Optimizer` as a superclass to `Lookahead`.
We don't need the line `self.param_groups = self.optimizer.param_groups` as that is done inside `torch.optim.Optimizer.__init__`.
N/A
> [Fix] Make Lookahead a subclass of Optimizer

- README.md
- docs/changelogs/v3.0.0.md
- docs/lr_scheduler.md
- pytorch_optimizer/__init__.py
- pytorch_optimizer/base/scheduler.py
- pytorch_optimizer/lr_scheduler/rex.py
- tests/test_load_modules.py
- tests/test_lr_schedulers.py
> [Feature] Implement REX lr scheduler

- pytorch_optimizer/optimizer/srmm.py
At step `memeory_length+1` it causes a `0**-beta` which is not allowed.
Move the `+1` to outside the mod expression
no
I think this was just a logic error but let me know if I'm incorrect since I'm not investigating this specific optimizer; I'm working on test harness to compare all optimizers.
> [Bugfix] Fix SRMM to allow operation beyond memory_length

- pytorch_optimizer/optimizer/utils.py
close #239
Replaced `|` with `Union` type.
> fix: reg_noise typing

- pytorch_optimizer/optimizer/lookahead.py
#fixes kozistr/pytorch_optimizer#237
Changed `param_groups` attribute to a property.
> fix: change Lookahead's param_groups to a property

- README.md
- docs/changelogs/v3.0.2.md
- docs/index.md
- docs/optimizer.md
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/adamw.py
- pytorch_optimizer/optimizer/utils.py
- tests/constants.py
- tests/test_load_modules.py
- tests/test_optimizers.py
> [Feature] Implement StableAdamW optimizer

- README.md
- docs/changelogs/v3.0.2.md
- docs/index.md
- docs/optimizer.md
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/base/optimizer.py
- pytorch_optimizer/optimizer/adam_mini.py
- tests/constants.py
- tests/test_base.py
- tests/test_gradients.py
- tests/test_load_modules.py
- tests/test_optimizers.py
> [Feature] Implement AdamMini optimizer

- pytorch_optimizer/optimizer/adam_mini.py
3 bugs for Adam-Mini
Keyerror `dim` → `dimension`
add_ unexpected arg `value` → `alpha`
fix when m =[] cant use mul_()
> [BUG Fix]Fix 3 bugs for Adam-Mini

- poetry.lock
- pyproject.toml
- pytorch_optimizer/optimizer/rotograd.py
- pytorch_optimizer/optimizer/shampoo.py
- pytorch_optimizer/optimizer/shampoo_utils.py
related to #100
* Windows 10, GTX 1060 6GB, torch 2.3.0+cu121
* random 2048 x 2048 matrix, repeat 100 times
* as-is: `1.58s`
* to-be: `1.12s`
> [Refactor] Stuffs

- docs/changelogs/v3.1.1.md
- pytorch_optimizer/optimizer/adamg.py
- pytorch_optimizer/optimizer/adan.py
- pytorch_optimizer/optimizer/alig.py
- pytorch_optimizer/optimizer/dadapt.py
- pytorch_optimizer/optimizer/lamb.py
- pytorch_optimizer/optimizer/prodigy.py
- pytorch_optimizer/optimizer/utils.py
- tests/constants.py
fixes #266 
all parameters are not on the same device.
N/A
N/A
> [Fix] device mismatch problems

- README.md
- docs/changelogs/v3.2.0.md
- docs/index.md
- pytorch_optimizer/__init__.py
- tests/test_create_optimizer.py
> [Feature] Support 8/4bit, fp8 optimizers

- pytorch_optimizer/optimizer/utils.py
- tests/test_utils.py
The `wd_ban_list` argument for `get_optimizer_parameters()` is somewhat misleading. When you look at it, you would expect any of the default arguments' name-formats to work correctly. However, that is not the case.
```py
wd_ban_list: List[str] = ('bias', 'LayerNorm.bias', 'LayerNorm.weight')
``` 
From this list, only `bias` is "detected" and "banned" correctly. Neither `LayerNorm.bias` is detected, nor is `LayerNorm.weight`. Neither of these parameters have their `weight_decay` set to 0. 
I even tested `LayerNorm` - and that doesn't work, either.
The reason this fails is that the `wd_ban_list` logic is only checking for the actual, fully-qualified parameter names; it is NOT checking for the class name of each `nn.Module`, as `pytorch_optimizer`'s default arguments and tests would imply.
I …
> [Fix] Implement better `wd_ban_list` handling

- pytorch_optimizer/lr_scheduler/linear_warmup.py
The `PolySchedulerWithWarmup` raises the following error:
```shell
TypeError: PolySchedulerWithWarmup.__init__() got multiple values for argument 'poly_order'
```
Reproduce the error:
```python
optimizer = torch.optim.SGD(
[torch.nn.Parameter(torch.randn(2, 2, requires_grad=True))], lr=0.1
)
poly_scheduler = PolyScheduler(
optimizer,
t_max=100,
max_lr=0.1,
min_lr=0.01,
init_lr=0.0,
warmup_steps=10,
poly_order=2.0,
)
```
Add optimizer parameter to PolyScheduler constructor.
N/A
> [Fix] Add optimizer parameter to PolyScheduler constructor.

- docs/changelogs/v3.3.1.md
- pyproject.toml
- tests/constants.py
- tests/test_optimizers.py
Close #313 
N/A
release v3.3.1
> [Feature] Implement MARS optimizer

- pytorch_optimizer/optimizer/soap.py
After https://github.com/kozistr/pytorch_optimizer/pull/333 SOAP functions correctly, but it has significant excess VRAM usage when training models with reduced precision weights (e.g. `bfloat16`).
This PR initializes and updates the condition matrices based on the precision of the parameters themselves rather than defaulting to `float32` for everything.
Note that the only exception to this is [the QR factorization to get the orthogonal Q](https://pytorch.org/docs/stable/generated/torch.linalg.qr.html) is done in `float32`, regardless of the underlying matrix precision, as 
- only `float32` has CUDA kernel support as of PyTorch 2.5.1
- precision matters for making the matrix actually orthogonal (I attempted to hand-roll Newton iteration but it was causing NaNs during optimization)
> [Feature] Store SOAP condition matrices as the dtype of their parameters

- README.md
- docs/changelogs/v3.4.1.md
- docs/index.md
- docs/optimizer.md
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/__init__.py
- pytorch_optimizer/optimizer/sam.py
- tests/constants.py
- tests/test_gradients.py
- tests/test_optimizer_parameters.py
- tests/test_optimizers.py
> [Feature] Implement `GCSAM` and `LookSAM` optimizers

- docs/changelogs/v3.4.1.md
- pytorch_optimizer/optimizer/adopt.py
- pytorch_optimizer/optimizer/experimental/ranger25.py
- tests/constants.py
> [Fix] Updating `exp_avg_sq` after calculating the `denominator` in `ADOPT` optimizer

- docs/changelogs/v3.5.0.md
- pytorch_optimizer/optimizer/schedulefree.py
- tests/test_optimizers.py
> [Fix] ScheduleFreeWrapper

- docs/changelogs/v3.6.1.md
- pytorch_optimizer/optimizer/scion.py
- tests/constants.py
momentum should be used instead of the gradient for the input of the LMO.
N/A
N/A
> [Fix] momentum in SCION optimizer

- pytorch_optimizer/optimizer/spam.py
1. **Norm Function Replacement**  
`torch.norm(grad)` → `torch.linalg.norm(grad)`  
Uses the updated PyTorch API for vector norm calculation.
2. **Zero Gradient Handling**  
Adds a check to skip parameter updates when `grad_norm == 0`. This:
- Avoids division-by-zero in subsequent calculations
- Optimizes performance by skipping unnecessary operations
- Maintains correctness (zero gradients imply no update needed)
> Fix NaN problem when Grad Norm is zero.
