- .pylintrc
- README.rst
- pytorch_optimizer/__init__.py
- pytorch_optimizer/adabelief.py
- pytorch_optimizer/adabound.py
- pytorch_optimizer/adahessian.py
- pytorch_optimizer/adamp.py
- pytorch_optimizer/agc.py
- pytorch_optimizer/chebyshev_schedule.py
- pytorch_optimizer/diffgrad.py
- pytorch_optimizer/lookahead.py
- pytorch_optimizer/madgrad.py
- pytorch_optimizer/radam.py
- pytorch_optimizer/ranger.py
- pytorch_optimizer/ranger21.py
- pytorch_optimizer/sam.py
- pytorch_optimizer/sgdp.py
- pytorch_optimizer/utils.py
- setup.py
* Implement `DiffGrad` optimizer
* Refactor the whole codes
* pylint score to 9.73/10
> [Feature] Implement DiffGrad optimizer

- pytorch_optimizer/__init__.py
- pytorch_optimizer/diffrgrad.py
- pytorch_optimizer/radam.py
- setup.py
Reference : https://github.com/lessw2020/Best-Deep-Learning-Optimizers/blob/master/diffgrad/diff_rgrad.py
> [Feature] Implement DiffRGrad optimizer

- pytorch_optimizer/adabelief.py
- pytorch_optimizer/adabound.py
- pytorch_optimizer/adahessian.py
- pytorch_optimizer/adamp.py
- pytorch_optimizer/agc.py
- pytorch_optimizer/diffgrad.py
- pytorch_optimizer/diffrgrad.py
- pytorch_optimizer/madgrad.py
- pytorch_optimizer/radam.py
- pytorch_optimizer/ranger.py
- pytorch_optimizer/sam.py
- pytorch_optimizer/sgdp.py
- pytorch_optimizer/utils.py
* `is_valid_parameters()` module
* explicit float expression (1 to 1.0)
> [Refactor] Type hint

- README.rst
- pytorch_optimizer/__init__.py
- pytorch_optimizer/fp16.py
- pytorch_optimizer/optimizers.py
- pytorch_optimizer/utils.py
* suggestion : #36 
* reference : https://github.com/facebookresearch/ParlAI/blob/main/parlai/utils/fp16.py
> [Feature] Support FP16 for all optimizers by utilizing wrapper class

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- Pipfile
- Pipfile.lock
- pytorch_optimizer/__init__.py
- pytorch_optimizer/adabelief.py
- pytorch_optimizer/diffrgrad.py
- requirements-dev.txt
- requirements.txt
- setup.py
* Support Python 3.6
* Add Python 3.9 CI
* `AdamD` to the classifiers
> [Deps] Update the dependencies

- .github/workflows/ci.yml
- Makefile
- Pipfile
- Pipfile.lock
- README.rst
- pytorch_optimizer/adahessian.py
- pytorch_optimizer/ranger.py
- requirements-dev.txt
- tests/test_optimizers.py
> [CI] Add pytest & codecov

- pytorch_optimizer/adabound.py
- pytorch_optimizer/diffgrad.py
- pytorch_optimizer/diffrgrad.py
- pytorch_optimizer/optimizers.py
- pytorch_optimizer/radam.py
- tests/test_load_optimizers.py
* test cases for load_optimizers
> [Test] Add test case for load_optimizers

- pytorch_optimizer/adahessian.py
- pytorch_optimizer/agc.py
- pytorch_optimizer/gc.py
- pytorch_optimizer/madgrad.py
- pytorch_optimizer/ranger21.py
- pytorch_optimizer/sam.py
- tests/test_optimizers.py
* Add SAM test cases
* Add FP16 test cases
> [Test] Add FP16 & SAM test cases

- pytorch_optimizer/adabelief.py
- pytorch_optimizer/adabound.py
- pytorch_optimizer/adahessian.py
- pytorch_optimizer/adamp.py
- pytorch_optimizer/base_optimizer.py
- pytorch_optimizer/diffgrad.py
- pytorch_optimizer/diffrgrad.py
- pytorch_optimizer/lamb.py
- pytorch_optimizer/lars.py
- pytorch_optimizer/madgrad.py
- pytorch_optimizer/radam.py
- pytorch_optimizer/ralamb.py
- pytorch_optimizer/ranger.py
- pytorch_optimizer/ranger21.py
- pytorch_optimizer/sam.py
- pytorch_optimizer/sgdp.py
- tests/test_optimizer_parameters.py
- tests/test_optimizers.py
- tests/test_sparse_gradient.py
Need to unify the validation function.
nope
nope
> [Refactor] BaseOptimizer

- README.rst
> [Docs] README

- Makefile
- poetry.lock
- pyproject.toml
loosen the version of `torch` dependency to `1.10`
version to 1.1.4
> [Build] update dependencies

- README.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/adan.py
- tests/test_load_optimizers.py
- tests/test_optimizer_parameters.py
- tests/test_optimizers.py
- tests/test_sparse_gradient.py
new feature, `Adan` optimizer
* [paper](https://arxiv.org/pdf/2208.06677.pdf)
nope
version to 1.2.0
> [Feature] Implement Adan optimizer

- README.rst
citations take a huge part of the readme, cause hard to read.
nope
nope
> [Docs] citations

- pytorch_optimizer/optimizer/ranger21.py
- tests/test_optimizer_parameters.py
- tests/test_optimizers.py
new feature for Ranger21 optimizer
nope
> [Feature] Ranger21 with AdamD

- README.rst
- docs/optimizer_api.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/lion.py
- tests/constants.py
- tests/test_load_optimizers.py
- tests/test_optimizer_parameters.py
implement a new optimizer, lion optimizer. (related to #110)
nope
bump version to v2.5.0
> [Feature] Lion optimizer

- README.rst
- docs/optimizer_api.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/adams.py
- pytorch_optimizer/optimizer/alig.py
- pytorch_optimizer/optimizer/gsam.py
- pytorch_optimizer/optimizer/lion.py
- pytorch_optimizer/optimizer/madgrad.py
- pytorch_optimizer/optimizer/novograd.py
- pytorch_optimizer/optimizer/utils.py
- tests/constants.py
- tests/test_create_optimizer.py
- tests/test_gradients.py
- tests/test_load_optimizers.py
- tests/test_optimizer_parameters.py
- tests/test_optimizers.py
- tests/test_utils.py
Implement Ali-G optimizer (related to #115)
nope
> [Feature] Implement Ali-G optimizer

- .github/workflows/ci.yml
- pytorch_optimizer/optimizer/lookahead.py
- pytorch_optimizer/optimizer/nero.py
- pytorch_optimizer/optimizer/utils.py
- tests/test_gradients.py
- tests/test_optimizer_parameters.py
> [Update] Add epsilon to stablize the optimizng

- pytorch_optimizer/optimizer/ranger21.py
- tests/test_optimizer_parameters.py
> [Refactor] Ranger21 optimizer

- docs/util_api.rst
- pytorch_optimizer/__init__.py
- pytorch_optimizer/base/exception.py
- pytorch_optimizer/optimizer/alig.py
- pytorch_optimizer/optimizer/shampoo.py
- pytorch_optimizer/optimizer/shampoo_utils.py
- tests/test_optimizers.py
- tests/test_utils.py
refactor/optimize scalable shampoo optimize
nope
> [Refactor] Refactor/Optimize Scalable Shampoo optimizer

- pyproject.toml
- pytorch_optimizer/optimizer/adafactor.py
- pytorch_optimizer/optimizer/sm3.py
related to #131
nope
bump version into v2.6.1
> [Fix] variables are not located on the same device with the gradients

- README.rst
- docs/optimizer_api.rst
- pytorch_optimizer/__init__.py
- pytorch_optimizer/base/optimizer.py
- pytorch_optimizer/optimizer/a2grad.py
- pytorch_optimizer/optimizer/sam.py
- tests/constants.py
- tests/test_load_optimizers.py
- tests/test_optimizer_parameters.py
implement A2Grad optimizer
nope
nope
> [Feature] Implement A2Grad optimizer

- README.rst
- docs/optimizer_api.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/base/optimizer.py
- pytorch_optimizer/optimizer/sgd.py
- tests/constants.py
- tests/test_general_optimizer_parameters.py
- tests/test_load_optimizers.py
- tests/test_optimizer_parameters.py
implement Accelerated SGD optimizer, #138 
nope
nope
> [Feature] Implement Accelerated SGD optimizer

- README.rst
- docs/optimizer_api.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/adamp.py
- pytorch_optimizer/optimizer/adanorm.py
- pytorch_optimizer/optimizer/swats.py
- tests/constants.py
- tests/test_load_optimizers.py
Implement SWATS optimizer, #138
nope
nope
> [Feature] Implement SWATS optimizer

- README.rst
- docs/optimizer_api.rst
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/fromage.py
- tests/constants.py
- tests/test_general_optimizer_parameters.py
- tests/test_gradients.py
- tests/test_load_optimizers.py
implement Fromage optimizer, #138 
nope
nope
> [Feature] Implement Fromage optimizer

- README.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/pid.py
- tests/constants.py
- tests/test_general_optimizer_parameters.py
- tests/test_load_optimizers.py
implement PID optimizer, #138
nope
bump version into v2.8.0
> [Feature] Implement PID optimizer

- README.rst
- docs/optimizer_api.rst
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/gravity.py
- tests/constants.py
- tests/test_general_optimizer_parameters.py
- tests/test_load_optimizers.py
- tests/test_optimizers.py
Implement Gravity optimizer
nope
nope
> [Feature] Implement Gravity optimizer

- README.rst
- docs/optimizer_api.rst
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/adasmooth.py
- pytorch_optimizer/optimizer/madgrad.py
- tests/constants.py
- tests/test_load_optimizers.py
implement AdaSmooth optimizer, #152
nope
> [Feature] Implement AdaSmooth optimizer

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- README.rst
- docs/optimizer_api.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/adadelta.py
- pytorch_optimizer/optimizer/dadapt.py
- tests/constants.py
- tests/test_load_optimizers.py
Implement AdaDelta optimizer
nope
bump version into v2.9.0
> [Feature] Implement AdaDelta optimizer

- .github/workflows/publish.yml
typo in `publish.yaml`
nope
need to re-deploy v2.9.1
> [Fix] Typo

- README.rst
- docs/optimizer_api.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/amos.py
- pytorch_optimizer/optimizer/dadapt.py
- tests/constants.py
- tests/test_general_optimizer_parameters.py
- tests/test_load_optimizers.py
- tests/test_optimizer_parameters.py
implement Amos optimizer
nope
nope
> [Feature] Implement Amos optimizer

- pytorch_optimizer/__init__.py
- pytorch_optimizer/base/optimizer.py
- pytorch_optimizer/base/types.py
- pytorch_optimizer/optimizer/adahessian.py
- pytorch_optimizer/optimizer/sgd.py
- pytorch_optimizer/optimizer/sophiah.py
- tests/test_general_optimizer_parameters.py
- tests/test_gradients.py
- tests/test_load_optimizers.py
- tests/test_optimizers.py
Solves https://github.com/kozistr/pytorch_optimizer/issues/173
https://github.com/kozistr/pytorch_optimizer/pull/175 only has SophiaG (which is more difficult to use due to Gauss-Newton-Bartlett estimator)
Added utility to compute Hutchinson's approximate Hessian
> Implement SophiaH & AdaHessian

- README.rst
- docs/base_api.rst
- docs/index.rst
- pytorch_optimizer/base/optimizer.py
- pytorch_optimizer/optimizer/adahessian.py
- pytorch_optimizer/optimizer/sgd.py
- pytorch_optimizer/optimizer/sophia.py
> [Refactor] Hessian methods

- README.rst
- docs/changelogs/v2.10.1.md
- docs/optimizer_api.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/base/optimizer.py
- pytorch_optimizer/optimizer/adasmooth.py
- pytorch_optimizer/optimizer/lars.py
- pytorch_optimizer/optimizer/prodigy.py
- pytorch_optimizer/optimizer/ranger.py
- tests/constants.py
- tests/test_general_optimizer_parameters.py
- tests/test_gradients.py
- tests/test_load_optimizers.py
- tests/test_optimizer_parameters.py
- tests/test_optimizers.py
related to #182 
bump version into v2.10.1
> [Feature] Implement Prodigy optimizer

- pytorch_optimizer/base/optimizer.py
> [Docs] Fix typo

- SECURITY.md
> [Docs] SECURITY.md

- README.rst
- docs/optimizer_api.rst
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/tiger.py
- tests/constants.py
- tests/test_general_optimizer_parameters.py
- tests/test_load_modules.py
> [Feature] Implement Tiger optimizer

- docs/index.md
- mkdocs.yml
> [Docs] Index page

- docs/.readthedocs.yaml
- docs/javascripts/tables.js
- mkdocs.yml
- requirements-docs.txt
> [Docs] Update documentation

- pyproject.toml
forgot to update the version
N/A
N/A
> [Update] v3.0.2

- pytorch_optimizer/optimizer/prodigy.py
- tests/test_optimizers.py
coverage
-[x] disable the line
N/A
N/A
> [Update] Coverage

- pyproject.toml
> [Release] v3.1.1

- docs/changelogs/v3.2.0.md
- pyproject.toml
> [Release] v3.2.0

- pyproject.toml
release v3.3.0
N/A
N/A
deploy v3.3.0
> [Release] v3.3.0

- README.md
- docs/changelogs/v3.3.1.md
- docs/index.md
- docs/optimizer.md
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/__init__.py
- pytorch_optimizer/optimizer/demo.py
- pytorch_optimizer/optimizer/muon.py
- tests/constants.py
- tests/test_create_optimizer.py
- tests/test_general_optimizer_parameters.py
- tests/test_gradients.py
- tests/test_load_modules.py
- tests/test_optimizers.py
implement Muon optimizer
N/A
N/A
> [Feature] Implement Muon optimizer

- pytorch_optimizer/optimizer/orthograd.py
Addresses this bug:
https://github.com/kozistr/pytorch_optimizer/issues/326
> fix OrthoGrad state management bug

- README.md
- docs/changelogs/v3.4.3.md
- docs/index.md
- docs/optimizer.md
- pyproject.toml
- pytorch_optimizer/__init__.py
- pytorch_optimizer/optimizer/__init__.py
- pytorch_optimizer/optimizer/spam.py
- tests/constants.py
- tests/test_load_modules.py
> [Feature] Implement StableSPAM optimizer

- docs/changelogs/v3.4.3.md
- pytorch_optimizer/optimizer/experimental/ranger25.py
- pytorch_optimizer/optimizer/sgd.py
- pytorch_optimizer/optimizer/sgdp.py
- pytorch_optimizer/optimizer/shampoo.py
- pytorch_optimizer/optimizer/sm3.py
- pytorch_optimizer/optimizer/soap.py
- pytorch_optimizer/optimizer/sophia.py
- pytorch_optimizer/optimizer/spam.py
- pytorch_optimizer/optimizer/srmm.py
- pytorch_optimizer/optimizer/swats.py
- pytorch_optimizer/optimizer/tam.py
- pytorch_optimizer/optimizer/tiger.py
- pytorch_optimizer/optimizer/yogi.py
> [Fix] potential bug in SPAM optimizer

- .github/workflows/ci.yml
- .github/workflows/copy-readme.yml
- .github/workflows/publish.yml
- README.md
- docs/index.md
> [CI] Copy `README.md` to `/docs/index.md` automatically

- docs/changelogs/v3.8.0.md
- docs/optimizer.md
- pytorch_optimizer/__init__.py
- pytorch_optimizer/base/optimizer.py
- pytorch_optimizer/optimizer/__init__.py
- pytorch_optimizer/optimizer/muon.py
- pytorch_optimizer/optimizer/utils.py
- requirements-docs.txt
- tests/test_create_optimizer.py
- tests/test_gradients.py
- tests/test_load_modules.py
- tests/test_utils.py
> [Feature] Implement `DistributedMuon` optimizer

- .github/workflows/pr_automerge.yml
- docs/changelogs/v3.8.1.md
- mkdocs.yml
- requirements-docs.txt
> [Docs] Upgrade the documentation page
